waterbirds_path: /media/disk1/Data/waterbirds
catdog: /media/disk1/Data/SpuriousCatDog
catdog2: /media/disk1/Data/SpuriousCatDogVer3
catdog4: /media/disk1/Data/SpuriousCatDogVer4
place365: /media/disk2/Data/Places365