land:
- 163.Cape_May_Warbler/Cape_May_Warbler_0028_163177.jpg
- 177.Prothonotary_Warbler/Prothonotary_Warbler_0124_173686.jpg
- 186.Cedar_Waxwing/Cedar_Waxwing_0118_178779.jpg
- 175.Pine_Warbler/Pine_Warbler_0007_171523.jpg
- 004.Groove_billed_Ani/Groove_Billed_Ani_0012_1784.jpg
- 163.Cape_May_Warbler/Cape_May_Warbler_0103_162972.jpg
- 054.Blue_Grosbeak/Blue_Grosbeak_0023_37069.jpg
- 197.Marsh_Wren/Marsh_Wren_0039_188201.jpg
- 129.Song_Sparrow/Song_Sparrow_0010_121331.jpg
- 019.Gray_Catbird/Gray_Catbird_0129_20987.jpg
- 042.Vermilion_Flycatcher/Vermilion_Flycatcher_0036_42389.jpg
- 076.Dark_eyed_Junco/Dark_Eyed_Junco_0086_66437.jpg
- 159.Black_and_white_Warbler/Black_And_White_Warbler_0115_160654.jpg
- 135.Bank_Swallow/Bank_Swallow_0037_129903.jpg
- 161.Blue_winged_Warbler/Blue_Winged_Warbler_0005_162095.jpg
- 099.Ovenbird/Ovenbird_0032_93199.jpg
- 020.Yellow_breasted_Chat/Yellow_Breasted_Chat_0039_21654.jpg
- 156.White_eyed_Vireo/White_Eyed_Vireo_0009_158830.jpg
- 121.Grasshopper_Sparrow/Grasshopper_Sparrow_0126_116029.jpg
- 074.Florida_Jay/Florida_Jay_0071_64993.jpg
- 188.Pileated_Woodpecker/Pileated_Woodpecker_0079_180388.jpg
- 171.Myrtle_Warbler/Myrtle_Warbler_0025_166704.jpg
- 163.Cape_May_Warbler/Cape_May_Warbler_0088_163149.jpg
- 011.Rusty_Blackbird/Rusty_Blackbird_0086_6658.jpg
- 029.American_Crow/American_Crow_0016_25112.jpg
- 132.White_crowned_Sparrow/White_Crowned_Sparrow_0064_126467.jpg
- 099.Ovenbird/Ovenbird_0104_92763.jpg
- 111.Loggerhead_Shrike/Loggerhead_Shrike_0029_104849.jpg
- 069.Rufous_Hummingbird/Rufous_Hummingbird_0047_59448.jpg
- 129.Song_Sparrow/Song_Sparrow_0110_120872.jpg
- 119.Field_Sparrow/Field_Sparrow_0029_113434.jpg
- 012.Yellow_headed_Blackbird/Yellow_Headed_Blackbird_0041_8264.jpg
- 143.Caspian_Tern/Caspian_Tern_0034_147643.jpg
- 071.Long_tailed_Jaeger/Long_Tailed_Jaeger_0029_61101.jpg
- 023.Brandt_Cormorant/Brandt_Cormorant_0076_23021.jpg
- 066.Western_Gull/Western_Gull_0094_55156.jpg
- 044.Frigatebird/Frigatebird_0004_43221.jpg
- 001.Black_footed_Albatross/Black_Footed_Albatross_0031_100.jpg
- 143.Caspian_Tern/Caspian_Tern_0059_145582.jpg
- 065.Slaty_backed_Gull/Slaty_Backed_Gull_0021_796008.jpg
- 072.Pomarine_Jaeger/Pomarine_Jaeger_0060_795756.jpg
- 064.Ring_billed_Gull/Ring_Billed_Gull_0017_51412.jpg
- 062.Herring_Gull/Herring_Gull_0039_46420.jpg
- 052.Pied_billed_Grebe/Pied_Billed_Grebe_0114_35493.jpg
- 146.Forsters_Tern/Forsters_Tern_0045_151227.jpg
- 006.Least_Auklet/Least_Auklet_0020_795080.jpg
- 045.Northern_Fulmar/Northern_Fulmar_0100_43732.jpg
- 072.Pomarine_Jaeger/Pomarine_Jaeger_0048_795771.jpg
- 142.Black_Tern/Black_Tern_0099_144242.jpg
- 101.White_Pelican/White_Pelican_0044_96028.jpg
- 066.Western_Gull/Western_Gull_0028_55680.jpg
- 102.Western_Wood_Pewee/Western_Wood_Pewee_0047_98274.jpg
- 023.Brandt_Cormorant/Brandt_Cormorant_0017_23141.jpg
- 063.Ivory_Gull/Ivory_Gull_0055_49353.jpg
- 090.Red_breasted_Merganser/Red_Breasted_Merganser_0063_79238.jpg
- 086.Pacific_Loon/Pacific_Loon_0019_75422.jpg
- 141.Artic_Tern/Artic_Tern_0065_141472.jpg
- 050.Eared_Grebe/Eared_Grebe_0058_34174.jpg
- 062.Herring_Gull/Herring_Gull_0114_46956.jpg
- 146.Forsters_Tern/Forsters_Tern_0062_151780.jpg
- 061.Heermann_Gull/Heermann_Gull_0073_45714.jpg
- 021.Eastern_Towhee/Eastern_Towhee_0093_22621.jpg
- 089.Hooded_Merganser/Hooded_Merganser_0014_796739.jpg
- 102.Western_Wood_Pewee/Western_Wood_Pewee_0026_98191.jpg
water:
- 077.Tropical_Kingbird/Tropical_Kingbird_0086_69759.jpg
- 181.Worm_eating_Warbler/Worm_Eating_Warbler_0022_176111.jpg
- 169.Magnolia_Warbler/Magnolia_Warbler_0053_165682.jpg
- 056.Pine_Grosbeak/Pine_Grosbeak_0082_38552.jpg
- 091.Mockingbird/Mockingbird_0050_80184.jpg
- 184.Louisiana_Waterthrush/Louisiana_Waterthrush_0018_177557.jpg
- 167.Hooded_Warbler/Hooded_Warbler_0135_164824.jpg
- 198.Rock_Wren/Rock_Wren_0027_189331.jpg
- 004.Groove_billed_Ani/Groove_Billed_Ani_0015_1653.jpg
- 077.Tropical_Kingbird/Tropical_Kingbird_0001_69958.jpg
- 018.Spotted_Catbird/Spotted_Catbird_0028_796813.jpg
- 037.Acadian_Flycatcher/Acadian_Flycatcher_0066_29190.jpg
- 083.White_breasted_Kingfisher/White_Breasted_Kingfisher_0011_73267.jpg
- 185.Bohemian_Waxwing/Bohemian_Waxwing_0072_177901.jpg
- 074.Florida_Jay/Florida_Jay_0003_65036.jpg
- 079.Belted_Kingfisher/Belted_Kingfisher_0053_70899.jpg
- 095.Baltimore_Oriole/Baltimore_Oriole_0130_89596.jpg
- 083.White_breasted_Kingfisher/White_Breasted_Kingfisher_0115_73252.jpg
- 042.Vermilion_Flycatcher/Vermilion_Flycatcher_0065_42467.jpg
- 125.Lincoln_Sparrow/Lincoln_Sparrow_0042_117507.jpg
- 128.Seaside_Sparrow/Seaside_Sparrow_0023_796525.jpg
- 022.Chuck_will_Widow/Chuck_Will_Widow_0055_796973.jpg
- 047.American_Goldfinch/American_Goldfinch_0086_31887.jpg
- 026.Bronzed_Cowbird/Bronzed_Cowbird_0054_24159.jpg
- 174.Palm_Warbler/Palm_Warbler_0061_169954.jpg
- 189.Red_bellied_Woodpecker/Red_Bellied_Woodpecker_0020_182335.jpg
- 159.Black_and_white_Warbler/Black_And_White_Warbler_0022_160512.jpg
- 119.Field_Sparrow/Field_Sparrow_0069_113827.jpg
- 133.White_throated_Sparrow/White_Throated_Sparrow_0085_129180.jpg
- 069.Rufous_Hummingbird/Rufous_Hummingbird_0045_59533.jpg
- 054.Blue_Grosbeak/Blue_Grosbeak_0051_37065.jpg
- 083.White_breasted_Kingfisher/White_Breasted_Kingfisher_0122_73199.jpg
- 051.Horned_Grebe/Horned_Grebe_0002_34577.jpg
- 023.Brandt_Cormorant/Brandt_Cormorant_0015_23198.jpg
- 060.Glaucous_winged_Gull/Glaucous_Winged_Gull_0023_45090.jpg
- 024.Red_faced_Cormorant/Red_Faced_Cormorant_0007_796280.jpg
- 063.Ivory_Gull/Ivory_Gull_0109_49382.jpg
- 058.Pigeon_Guillemot/Pigeon_Guillemot_0090_40090.jpg
- 144.Common_Tern/Common_Tern_0125_148767.jpg
- 058.Pigeon_Guillemot/Pigeon_Guillemot_0005_40375.jpg
- 061.Heermann_Gull/Heermann_Gull_0130_45700.jpg
- 106.Horned_Puffin/Horned_Puffin_0007_100699.jpg
- 052.Pied_billed_Grebe/Pied_Billed_Grebe_0096_35579.jpg
- 058.Pigeon_Guillemot/Pigeon_Guillemot_0081_40339.jpg
- 021.Eastern_Towhee/Eastern_Towhee_0021_22152.jpg
- 147.Least_Tern/Least_Tern_0095_154680.jpg
- 142.Black_Tern/Black_Tern_0061_143959.jpg
- 058.Pigeon_Guillemot/Pigeon_Guillemot_0055_40171.jpg
- 145.Elegant_Tern/Elegant_Tern_0032_150488.jpg
- 065.Slaty_backed_Gull/Slaty_Backed_Gull_0081_53264.jpg
- 058.Pigeon_Guillemot/Pigeon_Guillemot_0105_40078.jpg
- 005.Crested_Auklet/Crested_Auklet_0045_794940.jpg
- 059.California_Gull/California_Gull_0105_41116.jpg
- 143.Caspian_Tern/Caspian_Tern_0049_145755.jpg
- 021.Eastern_Towhee/Eastern_Towhee_0002_22318.jpg
- 051.Horned_Grebe/Horned_Grebe_0072_34497.jpg
- 086.Pacific_Loon/Pacific_Loon_0057_75854.jpg
- 100.Brown_Pelican/Brown_Pelican_0020_95422.jpg
- 061.Heermann_Gull/Heermann_Gull_0032_45774.jpg
- 002.Laysan_Albatross/Laysan_Albatross_0044_784.jpg
- 045.Northern_Fulmar/Northern_Fulmar_0098_43578.jpg
- 089.Hooded_Merganser/Hooded_Merganser_0040_78984.jpg
- 088.Western_Meadowlark/Western_Meadowlark_0104_78105.jpg
- 001.Black_footed_Albatross/Black_Footed_Albatross_0032_796115.jpg
