class_path: csr.module.FeatureExtractor
init_args:
  # DataModule
  dataset: null #required
  data_type: null #required
  data_dir: null #required
  data_seed: 1234
  num_workers: 2
  batch_size_train: 128
  batch_size_test: 100
  minor_ratio: 0.05
  subsample_what: null
  upsample_count: null
  upsample_indices_path: null
  # ERM
  model: convnext_t
  input_type: raw
  imagenet_pretrained: True
  model_path: null
  freeze_model: True
  freezing_target_layer: classifier.2
  set_last_layer: linear
  del_backbone: True
  h_activation_fn: softplus
  h_softplus_beta: 10
  learning_rate: 1e-3
  scheduler: cosineannealing
  milestones: [9999]
  weight_decay: 1e-2
  optimizer: adamw
  criterion: bce
  # FeatureExtractor
  save_root: null # required
  target_layer: classifier.1 # required